function(qpgi_add_test TEST_NAME TEST_SOURCES)
  add_executable(${TEST_NAME} ${TEST_SOURCES})
  target_link_libraries(${TEST_NAME} ${Boost_UNIT_TEST_FRAMEWORK_LIBRARIES})
  add_test(NAME ${TEST_NAME} COMMAND ${TEST_NAME})
endfunction()
